[workspace]
members = [ "blog_os", "burn_example", "deepLearning",
    "execlToJson",
    "hecto",
    "httpie", "leetcode",
    "myString",
    "queryer",
    "thumbor_rs",
    "web3test",
]


resolver = "2"